import type { LangContent } from './types';

export const CONTENT: Record<'en' | 'vi', LangContent> = {
  en: {
    nav: { hero: 'Index', about: 'About', skills: 'Skills', exp: 'Experience', projects: 'Work', agents: 'Agents', metrics: 'Numbers', awards: 'Awards', contact: 'Contact' },
    hero: {
      kicker: 'Hanoi, Vietnam — UTC+7',
      name: 'Cuong Manh Le',
      roles: ['Project Manager', 'Full-stack Developer', 'AI Product Builder'],
      tagline: 'Turning ambiguous product intent into shipped AI software — in days, not weeks.',
      cta_primary: 'See work',
      cta_secondary: 'Get in touch',
      meta: ['7+ yrs shipping', 'AI adoption consultant', 'Teams of 5–10 led'],
    },
    about: {
      label: '01 / About',
      title: 'Operating at the seam of product, UX & engineering.',
      body: 'I lead small, fast teams that take a fuzzy brief and ship a working AI product. I write the code, run the sprint, talk to the customer, and hand a clean spec to the next engineer. I work with Claude, GPT, Gemini and Copilot every day — not as a gimmick, but as a force multiplier across the whole stack.',
      stats: [
        { k: 'Years shipping', v: '7+' },
        { k: 'Teams led', v: '5–10' },
        { k: 'LLM providers in prod', v: '3' },
        { k: 'AI adoption projects', v: '10+' },
      ],
      mapLabel: 'Based in',
      mapCity: 'Hà Nội',
      mapCoord: '21.0285° N, 105.8542° E',
      mapNote: 'Available remote, GMT−5 → GMT+10 overlap.',
    },
    skills: {
      label: '02 / Skills',
      title: 'Three hats, one operator.',
      cards: [
        { tag: 'PM', title: 'Project Management', body: 'Roadmap, scope, stakeholders, risk. Agile/Scrum across AI SaaS, IoT, AR/VR and enterprise.', chips: ['Agile/Scrum','Roadmap','Sprint planning','Risk mgmt','Stakeholder mgmt','Cross-functional leadership','Jira','n8n'] },
        { tag: 'FS', title: 'Full-stack Engineering', body: 'Frontend lead background, comfortable from React to Postgres to GCP. Performance and 3D rendering my niche.', chips: ['React / Next.js','React Native','Node.js','Java Spring','PostgreSQL','MongoDB','GCP','Electron','Three.js','TypeScript'] },
        { tag: 'AI', title: 'AI Product Builder & Consultant', body: 'RAG pipelines, multi-agent orchestration, LLM-assisted delivery. I also advise businesses on adopting AI — from use-case discovery to production rollout.', chips: ['RAG','Claude Code','OpenAI','Anthropic','Gemini','Prompt eng.','n8n agents','Vector search','Multi-agent','AI consulting'] },
      ],
    },
    exp: {
      label: '03 / Experience',
      title: 'Track record.',
      items: [
        { y: 'May 2025 — Now', org: 'Afforai (Logically)', role: 'AI Product Builder / Project Leader', loc: 'Remote', body: 'Shipped AI-powered document tools (Logically, Cite Extension). Designed RAG pipelines on OpenAI/Anthropic/Gemini. Owned full stack — React, Node, Postgres, Mongo, GCP.' },
        { y: 'May 2024 — May 2025', org: 'Undisclosed Company', role: 'Fullstack Developer / Tech Lead', loc: 'Remote', body: 'Built and maintained web products end to end under NDA. React/TypeScript frontend, Node backend, Postgres & Mongo data layer, cloud deployment and CI/CD.' },
        { y: 'Dec 2020 — May 2024', org: 'FPT Telecom', role: 'Project Manager / Software Developer', loc: 'Hanoi', body: 'Led FPT Partner Platform (7 people), Coca-Cola AR Training (10 people), IRIS 3D Web/Desktop (Three.js + Electron), LearnR Blockchain — Top 5 Aura Hackathon 2022.' },
        { y: 'Oct 2019 — Nov 2020', org: 'Lumi Vietnam', role: 'Mobile Developer', loc: 'Hanoi', body: 'Built IoT mobile apps with React Native, BLE and MQTT. Owned iOS / Android release pipelines.' },
        { y: 'Jan 2018 — Oct 2019', org: 'DigiMed / VJ-Soft', role: 'Mobile Developer (Android + RN)', loc: 'Hanoi', body: 'Shipped mobile features end-to-end from Figma → prod. RESTful, Firebase, SQLite. Habit of documenting edge cases.' },
        { y: 'Jan 2018 — Jun 2018', org: 'FPT Polytechnic', role: 'Teaching Assistant', loc: 'Hanoi', body: 'Tutored Java, SQL, JavaScript, ReactJS, React Native to undergrad cohort.' },
      ],
    },
    projects: {
      label: '04 / Work',
      title: 'Selected work.',
      featured: {
        tag: 'LIVE — featured product',
        name: 'Logically',
        url: 'https://logically.app',
        urlLabel: 'logically.app',
        sub: 'AI document research, summarization & citation — used by researchers worldwide.',
        bullets: [
          'Designed RAG pipeline over OpenAI, Anthropic, Gemini, Serper, Semantic Scholar',
          'Built multi-collaborator editor on Tiptap + Hocuspocus',
          'Owned React + Node + Postgres + Mongo + GCP delivery end-to-end',
          'Took the product from early MVP to an established research tool in 18 months',
        ],
        stack: ['React','Node.js','Postgres','Mongo','GCP','OpenAI','Anthropic','Gemini','Tiptap','Stripe'],
      },
      grid: [
        { name: 'Afforai Cite Extension', role: 'Lead engineer', body: 'Microsoft Word add-in for inserting citations from a chatbot. React + MUI + Tiptap + Recoil.', chips: ['MS Word','React','MUI','Tiptap'] },
        { name: 'IRIS 3D Web/Desktop', role: 'Frontend lead — 5 ppl', body: 'Customize 3D avatars, accessories, scenes. Web + Windows shipped from one codebase.', chips: ['Three.js','Electron','React'] },
        { name: 'Coca-Cola AR Training', role: 'Project lead — 10 ppl', body: 'AR-based sales training for Coca-Cola Vietnam. Cross-functional team end-to-end.', chips: ['React Native','Unity','C#'] },
        { name: 'LearnR (Aura Hackathon)', role: 'Project lead — 5 ppl', body: 'Blockchain Learn2Earn dApp on Aura Network. Top 5 finalist, 2022.', chips: ['Rust','React','Node','Cosmjs'] },
        { name: 'Lumi IoT Suite', role: 'Mobile dev', body: 'Smart-home BLE + MQTT control across iOS/Android — Lumi Life, RaliSmart, Eureka.', chips: ['React Native','BLE','MQTT','Firebase'] },
        { name: 'Multi-Agent Delivery System', role: 'Architect', body: 'Orchestrated agents — BA → Planner → Dev → Reviewer → QA — with feedback loops, replacing manual handoffs.', chips: ['LLM','n8n','RAG','Orchestration'] },
      ],
    },
    agents: {
      label: '05 / Agents',
      title: 'Multi-Agent Product Delivery System',
      sub: 'A fully orchestrated pipeline that turns a user request into shipped code — without manual handoffs.',
      nodes: [
        { id: 'user', label: 'User request', sub: 'raw intent' },
        { id: 'ba', label: 'BA Agent', sub: 'scopes & clarifies' },
        { id: 'planner', label: 'Planner', sub: 'sprint + tasks' },
        { id: 'dev', label: 'Developer', sub: 'writes code' },
        { id: 'review', label: 'Reviewer', sub: 'audits + critiques' },
        { id: 'qa', label: 'QA Agent', sub: 'tests + bugfiles' },
        { id: 'ship', label: 'Delivery', sub: 'ship to user' },
      ],
      loops: ['Reviewer ↺ Developer', 'QA ↺ Developer'],
      note: 'Built daily with Claude Code, GPT, Gemini, n8n.',
    },
    metrics: {
      label: '06 / Numbers',
      title: 'Outcomes, not output.',
      items: [
        { v: '10+', k: 'AI adoption projects', sub: 'Consulting for SMEs & product teams' },
        { v: '3', k: 'LLM providers in prod', sub: 'OpenAI · Anthropic · Gemini' },
        { v: '7+', k: 'Years shipping', sub: 'AI, SaaS, IoT, AR/VR, enterprise' },
        { v: '10', k: 'Cross-functional team led', sub: 'Coca-Cola AR' },
        { v: 'Top 5', k: 'Aura Hackathon', sub: 'Blockchain track, 2022' },
        { v: '9.22', k: 'GPA / 10', sub: 'Valedictorian, FPT Polytechnic' },
      ],
    },
    awards: {
      label: '07 / Awards & Education',
      title: 'Recognition.',
      awards: [
        { y: '2022', t: 'Top 5 — Aura Network Hackathon', s: 'Blockchain / Web3 track' },
        { y: '2019', t: 'Valedictorian — FPT Polytechnic', s: 'Ranked 1st in graduating cohort' },
        { y: '2018', t: 'Best Student — Agile Software Project Management', s: 'FPT Polytechnic' },
        { y: '2018', t: 'Best Student — Advanced Android Programming', s: 'FPT Polytechnic' },
      ],
      edu: { school: 'FPT Polytechnic', degree: 'Diploma — Computer & Mobile Programming', years: '2017 — 2019', gpa: 'GPA 9.22 / 10 · 6 consecutive Excellent Student semesters' },
    },
    contact: {
      label: '08 / Contact',
      title: 'Got something ambiguous you need shipped?',
      sub: 'I read every email. Replies within 24h.',
      email: 'cuonglmfpt231096@gmail.com',
      phone: '+84 346 100 980',
      links: [
        { k: 'Email', v: 'cuonglmfpt231096@gmail.com', href: 'mailto:cuonglmfpt231096@gmail.com' },
        { k: 'Phone', v: '+84 346 100 980', href: 'tel:+84346100980' },
        { k: 'Live product', v: 'logically.app', href: 'https://logically.app' },
        { k: 'Location', v: 'Hanoi, Vietnam', href: null },
      ],
      cta: 'Send email',
      foot: 'Designed & built in Hanoi · 2026',
    },
  },
  vi: {
    nav: { hero: 'Mở đầu', about: 'Giới thiệu', skills: 'Kỹ năng', exp: 'Kinh nghiệm', projects: 'Dự án', agents: 'AI Agents', metrics: 'Số liệu', awards: 'Giải thưởng', contact: 'Liên hệ' },
    hero: {
      kicker: 'Hà Nội, Việt Nam — UTC+7',
      name: 'Lê Mạnh Cường',
      roles: ['Project Manager', 'Fullstack Developer', 'AI Product Builder'],
      tagline: 'Biến yêu cầu mơ hồ thành sản phẩm AI chạy được — tính bằng ngày, không phải tuần.',
      cta_primary: 'Xem dự án',
      cta_secondary: 'Liên hệ',
      meta: ['7+ năm ship sản phẩm', 'Tư vấn áp dụng AI', 'Lead team 5–10 người'],
    },
    about: {
      label: '01 / Giới thiệu',
      title: 'Đứng giữa Product, UX và Engineering.',
      body: 'Tôi dẫn các team nhỏ và nhanh, lấy một brief mơ hồ và ship được sản phẩm AI hoàn chỉnh. Tôi vừa code, vừa chạy sprint, vừa nói chuyện với khách, vừa bàn giao spec sạch cho engineer tiếp theo. Tôi dùng Claude, GPT, Gemini, Copilot mỗi ngày — không phải để trang trí, mà để nhân tốc độ trên toàn bộ stack.',
      stats: [
        { k: 'Năm kinh nghiệm', v: '7+' },
        { k: 'Quy mô team đã dẫn', v: '5–10' },
        { k: 'LLM provider trên production', v: '3' },
        { k: 'Dự án tư vấn AI', v: '10+' },
      ],
      mapLabel: 'Đang ở',
      mapCity: 'Hà Nội',
      mapCoord: '21.0285° N, 105.8542° E',
      mapNote: 'Sẵn sàng remote, lệch múi giờ GMT−5 → GMT+10.',
    },
    skills: {
      label: '02 / Kỹ năng',
      title: 'Ba vai, một người vận hành.',
      cards: [
        { tag: 'PM', title: 'Project Management', body: 'Roadmap, scope, stakeholder, rủi ro. Agile/Scrum trên AI SaaS, IoT, AR/VR và sản phẩm enterprise.', chips: ['Agile/Scrum','Roadmap','Sprint planning','Quản trị rủi ro','Stakeholder','Lãnh đạo đa chức năng','Jira','n8n'] },
        { tag: 'FS', title: 'Fullstack Engineering', body: 'Xuất thân Frontend Lead, thạo từ React tới Postgres tới GCP. Niche là performance và 3D rendering.', chips: ['React / Next.js','React Native','Node.js','Java Spring','PostgreSQL','MongoDB','GCP','Electron','Three.js','TypeScript'] },
        { tag: 'AI', title: 'AI Product Builder & Consultant', body: 'RAG pipeline, multi-agent orchestration, LLM-assisted delivery. Tư vấn doanh nghiệp áp dụng AI — từ tìm use-case tới triển khai production.', chips: ['RAG','Claude Code','OpenAI','Anthropic','Gemini','Prompt eng.','n8n agents','Vector search','Multi-agent','Tư vấn AI'] },
      ],
    },
    exp: {
      label: '03 / Kinh nghiệm',
      title: 'Track record.',
      items: [
        { y: '5/2025 — Nay', org: 'Afforai (Logically)', role: 'AI Product Builder / Project Leader', loc: 'Remote', body: 'Ship sản phẩm AI xử lý tài liệu (Logically, Cite Extension). Thiết kế RAG trên OpenAI/Anthropic/Gemini. Owner toàn stack — React, Node, Postgres, Mongo, GCP.' },
        { y: '5/2024 — 5/2025', org: 'Công ty ẩn danh', role: 'Fullstack Developer / Tech Lead', loc: 'Remote', body: 'Xây và vận hành sản phẩm web end-to-end theo NDA. Frontend React/TypeScript, backend Node, dữ liệu Postgres & Mongo, triển khai cloud và CI/CD.' },
        { y: '12/2020 — 5/2024', org: 'FPT Telecom', role: 'Project Manager / Software Developer', loc: 'Hà Nội', body: 'Dẫn FPT Partner Platform (7 người), Coca-Cola AR Training (10 người), IRIS 3D Web/Desktop (Three.js + Electron), LearnR Blockchain — Top 5 Aura Hackathon 2022.' },
        { y: '10/2019 — 11/2020', org: 'Lumi Vietnam', role: 'Mobile Developer', loc: 'Hà Nội', body: 'Build app IoT bằng React Native, BLE và MQTT. Owner release pipeline iOS / Android.' },
        { y: '1/2018 — 10/2019', org: 'DigiMed / VJ-Soft', role: 'Mobile Developer (Android + RN)', loc: 'Hà Nội', body: 'Ship feature mobile end-to-end từ Figma → production. RESTful, Firebase, SQLite. Thói quen document edge case.' },
        { y: '1/2018 — 6/2018', org: 'FPT Polytechnic', role: 'Trợ giảng', loc: 'Hà Nội', body: 'Trợ giảng Java, SQL, JavaScript, ReactJS, React Native cho sinh viên đại học.' },
      ],
    },
    projects: {
      label: '04 / Dự án',
      title: 'Dự án nổi bật.',
      featured: {
        tag: 'ĐANG VẬN HÀNH — sản phẩm chính',
        name: 'Logically',
        url: 'https://logically.app',
        urlLabel: 'logically.app',
        sub: 'AI nghiên cứu, tóm tắt và trích dẫn tài liệu — phục vụ researcher toàn cầu.',
        bullets: [
          'Thiết kế RAG pipeline trên OpenAI, Anthropic, Gemini, Serper, Semantic Scholar',
          'Build editor đa người dùng trên Tiptap + Hocuspocus',
          'Owner toàn bộ delivery React + Node + Postgres + Mongo + GCP',
          'Đưa sản phẩm từ MVP thành công cụ nghiên cứu có chỗ đứng trong 18 tháng',
        ],
        stack: ['React','Node.js','Postgres','Mongo','GCP','OpenAI','Anthropic','Gemini','Tiptap','Stripe'],
      },
      grid: [
        { name: 'Afforai Cite Extension', role: 'Lead engineer', body: 'Add-in Microsoft Word để chèn citation từ chatbot. React + MUI + Tiptap + Recoil.', chips: ['MS Word','React','MUI','Tiptap'] },
        { name: 'IRIS 3D Web/Desktop', role: 'Frontend lead — 5 người', body: 'Tuỳ biến avatar 3D, phụ kiện, scene. Web + Windows ship chung một codebase.', chips: ['Three.js','Electron','React'] },
        { name: 'Coca-Cola AR Training', role: 'Project lead — 10 người', body: 'Đào tạo sales AR cho Coca-Cola Vietnam. Team đa chức năng end-to-end.', chips: ['React Native','Unity','C#'] },
        { name: 'LearnR (Aura Hackathon)', role: 'Project lead — 5 người', body: 'dApp Learn2Earn trên Aura Network. Top 5 chung kết, 2022.', chips: ['Rust','React','Node','Cosmjs'] },
        { name: 'Lumi IoT Suite', role: 'Mobile dev', body: 'Điều khiển nhà thông minh BLE + MQTT trên iOS/Android — Lumi Life, RaliSmart, Eureka.', chips: ['React Native','BLE','MQTT','Firebase'] },
        { name: 'Multi-Agent Delivery System', role: 'Architect', body: 'Orchestrate agent — BA → Planner → Dev → Reviewer → QA — có feedback loop, thay thế bàn giao thủ công.', chips: ['LLM','n8n','RAG','Orchestration'] },
      ],
    },
    agents: {
      label: '05 / AI Agents',
      title: 'Multi-Agent Product Delivery System',
      sub: 'Pipeline orchestrate đầy đủ: từ yêu cầu user → code đã ship, không cần bàn giao thủ công.',
      nodes: [
        { id: 'user', label: 'User request', sub: 'yêu cầu thô' },
        { id: 'ba', label: 'BA Agent', sub: 'scope & clarify' },
        { id: 'planner', label: 'Planner', sub: 'sprint + task' },
        { id: 'dev', label: 'Developer', sub: 'viết code' },
        { id: 'review', label: 'Reviewer', sub: 'audit + góp ý' },
        { id: 'qa', label: 'QA Agent', sub: 'test + báo bug' },
        { id: 'ship', label: 'Delivery', sub: 'ship cho user' },
      ],
      loops: ['Reviewer ↺ Developer', 'QA ↺ Developer'],
      note: 'Xây hàng ngày với Claude Code, GPT, Gemini, n8n.',
    },
    metrics: {
      label: '06 / Số liệu',
      title: 'Outcome, không phải output.',
      items: [
        { v: '10+', k: 'Dự án tư vấn AI', sub: 'Cho SME & product team' },
        { v: '3', k: 'LLM provider trên production', sub: 'OpenAI · Anthropic · Gemini' },
        { v: '7+', k: 'Năm ship sản phẩm', sub: 'AI, SaaS, IoT, AR/VR, enterprise' },
        { v: '10', k: 'Quy mô team đã dẫn', sub: 'Coca-Cola AR' },
        { v: 'Top 5', k: 'Aura Hackathon', sub: 'Blockchain track, 2022' },
        { v: '9.22', k: 'GPA / 10', sub: 'Thủ khoa FPT Polytechnic' },
      ],
    },
    awards: {
      label: '07 / Giải thưởng & Học vấn',
      title: 'Recognition.',
      awards: [
        { y: '2022', t: 'Top 5 — Aura Network Hackathon', s: 'Blockchain / Web3 track' },
        { y: '2019', t: 'Thủ khoa — FPT Polytechnic', s: 'Xếp thứ 1 toàn khoá tốt nghiệp' },
        { y: '2018', t: 'Best Student — Agile Software Project Management', s: 'FPT Polytechnic' },
        { y: '2018', t: 'Best Student — Advanced Android Programming', s: 'FPT Polytechnic' },
      ],
      edu: { school: 'FPT Polytechnic', degree: 'Diploma — Computer & Mobile Programming', years: '2017 — 2019', gpa: 'GPA 9.22 / 10 · 6 kỳ liên tiếp đạt sinh viên xuất sắc' },
    },
    contact: {
      label: '08 / Liên hệ',
      title: 'Có vấn đề mơ hồ cần ship?',
      sub: 'Tôi đọc mọi email. Phản hồi trong 24h.',
      email: 'cuonglmfpt231096@gmail.com',
      phone: '+84 346 100 980',
      links: [
        { k: 'Email', v: 'cuonglmfpt231096@gmail.com', href: 'mailto:cuonglmfpt231096@gmail.com' },
        { k: 'Phone', v: '+84 346 100 980', href: 'tel:+84346100980' },
        { k: 'Live product', v: 'logically.app', href: 'https://logically.app' },
        { k: 'Vị trí', v: 'Hà Nội, Việt Nam', href: null },
      ],
      cta: 'Gửi email',
      foot: 'Thiết kế & build tại Hà Nội · 2026',
    },
  },
};
